version: "3"
services:
    php:
        image: matthiasnoback/decoupling-workshop-php
        build: docker/php/
        volumes:
            - ./:/app
        entrypoint: php
        user: ${HOST_UID}:${HOST_GID}
        env_file:
            - .env
        init: true

    web:
        image: matthiasnoback/decoupling-workshop-web
        build: docker/web/
        volumes:
            - ./:/app
        ports:
            # Development server
            - "8080:8080"
        expose:
            - 8080
        user: ${HOST_UID}:${HOST_GID}
        env_file:
            - .env

    composer:
        image: composer:latest
        volumes:
            - ./:/app
        user: ${HOST_UID}:${HOST_GID}
        env_file:
            - .env
